# Matrix Modification Operations

### Imports

In [1]:
import numpy as np

### Variables

In [2]:
# Base matrix variable
a_matrix = np.matrix([ [ 1, 2 ], [ 3, 4 ] ])

# Change matrix value in the second matrix first position to 10
a_matrix[ 1, 0 ] = 10

# Change entire first matrix values
a_matrix[ 0 ] = [ 6, 3 ]

a_matrix_original = np.matrix([ [ 1, 2 ], [ 3, 4 ] ])
added_matrix = np.add( a_matrix, a_matrix_original )
multiplied_matrix = np.matmul( a_matrix, a_matrix_original )


### Display Data

In [4]:
# Sorting in descending order 
print( -np.sort( -a_matrix ), "\n" )

print( a_matrix_original.T ) # Transpose the matrix
print( a_matrix_original.flatten(), "\n" ) # Flattens the matrix from 2x2 to 1x4

print( a_matrix_original + 1 ) # Adds 1 to every value in the matrices
print( a_matrix_original * 2, "\n" ) # Multiplies by 2 every value in the matrices

# Add two matrices together
print( added_matrix, "\n" )

# Multiply matrices
print( multiplied_matrix )

[[ 6  3]
 [10  4]] 

[[1 3]
 [2 4]]
[[1 2 3 4]] 

[[2 3]
 [4 5]]
[[2 4]
 [6 8]] 

[[ 7  5]
 [13  8]] 

[[15 24]
 [22 36]]
