# Matrix Fetch Operations

### Imports

In [1]:
import numpy as np

### Variables

In [2]:
a_matrix = np.matrix( [ [ 1, 2, 3 ], [ 4, 5, 6 ], [ 7, 8, 9 ] ] )

### Display Data

In [8]:
print( a_matrix, "\n" )

print( a_matrix[0], "\n )
print( a_matrix[1, 0] )
print( a_matrix[2, 1:3], "\n" )

print( a_matrix.size, )
print( a_matrix.shape, "\n" )

print( np.amax( a_matrix ) )
print( np.amin( a_matrix ) )
print( np.average( a_matrix ) )

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]] 

4
[[8 9]] 

9
(3, 3) 

9
1
5.0


### Same result, slightly different syntax

In [5]:
print( a_matrix.max() )
print( a_matrix.min() )
print( a_matrix.mean() )

9
1
5.0
