# Matrix Example with Images

### Imports

In [1]:
import numpy as np

### Variables


In [3]:
image_matrix = np.matrix([ [ 0, 0, 1, 0, 0 ], [ 0, 0, 1, 0, 0 ], [ 1, 1, 1, 1, 1 ], [ 0, 0, 1, 0, 0 ], [ 0, 0, 1, 0, 0 ] ])

rows = image_matrix.shape[0]
columns = image_matrix.shape[1]


### Displaying data


In [8]:
# Print value of rows and columns
print( "Number of rows: ", rows )
print( "Number of columns: ", columns )
print( "\n" )

# Reverse 1's and 0's values
for row in range( rows ):
    for column in range( columns ):
        if image_matrix[ row, column ] == 0:
            image_matrix[ row, column ] = 1
        else:
            image_matrix[ row, column ] = 0

print( "Inverted Image Matrix:")
print( image_matrix )
print( "\n" )

# Transpose matrix
print( "Transposed Matrix: ", "\n", image_matrix.T )
print( "\n" )

# Flatten matrix
print( "Flattened Matrix: ", "\n", image_matrix.flatten() )

Number of rows:  5
Number of columns:  5


Inverted Image Matrix:
[[1 1 0 1 1]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 1]]


Transposed Matrix:  
 [[1 1 0 1 1]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 1]]


Flattened Matrix:  
 [[1 1 0 1 1 1 1 0 1 1 0 0 0 0 0 1 1 0 1 1 1 1 0 1 1]]
